Missing API entries on the wrappers
FloatingArrayDesign/MoorDyn pull request #262
Opened 2024-10-21 06:56 UTC by sanguinariojoe

Just a couple of API entries that were missing on the wrappers. Notes:

 - I compiled Python and Fortran. Can anybody try to compile the matlab one?
 - I did not check any of them (related: https://github.com/FloatingArrayDesign/MoorDyn/issues/203)

2024-10-21 14:31 UTC, RyanDavies19 commented
@sanguinariojoe after fixing the two redefinition errors Matlab compiled fine for me! (MacOS, Apple Silicon, MATLAB 24.1.0.2628055)

2024-10-22 15:04 UTC, RyanDavies19 commented
They're clang errors, not Matlab. 

`MoorDyn/wrappers/matlab/MoorDynM_Serialize.cpp:46:12: error: redefinition of 'err'`
`MoorDyn/wrappers/matlab/MoorDynM_GetTimeScheme.cpp:46:12: error: redefinition of 'err'`

2024-10-23 04:42 UTC, sanguinariojoe commented
> They're clang errors, not Matlab.
> 
> `MoorDyn/wrappers/matlab/MoorDynM_Serialize.cpp:46:12: error: redefinition of 'err'` `MoorDyn/wrappers/matlab/MoorDynM_GetTimeScheme.cpp:46:12: error: redefinition of 'err'`

Thanks! It should work fine now

2024-10-23 13:45 UTC, RyanDavies19 requested changes

2024-10-23 13:45 UTC, RyanDavies19 commented on wrappers/matlab/MoorDynM_GetTimeScheme.cpp
> +	int err = MoorDyn_GetTimeScheme(instance, NULL, &name_len);
Here (line 44) and line 47 still have a redefinition of err. Need to remove the `int` declaration

2024-10-23 13:46 UTC, RyanDavies19 commented
@sanguinariojoe I think you forgot to get rid of the `int` declaration in `GetTimeScheme`, its still throwing the compile errors. I flagged it with a comment.

Other than that it looks good!

2024-10-24 04:16 UTC, sanguinariojoe commented
> @sanguinariojoe I think you forgot to get rid of the `int` declaration in `GetTimeScheme`, its still throwing the compile errors. I flagged it with a comment.
> 
> Other than that it looks good!

Geez! I am becoming dumber and dumber...

2024-10-24 04:23 UTC, merged

2024-10-24 15:11 UTC, RyanDavies19 commented
> > @sanguinariojoe I think you forgot to get rid of the `int` declaration in `GetTimeScheme`, its still throwing the compile errors. I flagged it with a comment.
> > Other than that it looks good!
> 
> Geez! I am becoming dumber and dumber...

Hahaha, thanks for doing this